### ISSUE TITLE
[Question] Generate resourceObject & Overall Usage

### ISSUE THREAD

**Issue by johannesschobel** [rmarganti/ts-json-api#4]
Dear @rmarganti,

thank you for this library - it really looks nice.
When i looked at the project description and tried to toy a bit around, i stumbled upon some questions - maybe you can help me with this?

I have created a `ProjectApi` interface that describes the "serialized data". It looks like this:
```ts
import {ResourceObject} from 'ts-json-api';

export interface ProjectApiModel extends ResourceObject {
  type: 'projects',
  id: string,
  attributes: {
    name: string,
    description: string,
    createdAt: Date,
    updatedAt: Date,
  },
}
```

In my controller i call a service that fetches respective projects from the database. However, my internal models may look different (e.g., i do not want to output all internal fields to clients).

In order to properly output my data, i then need to call:
```ts
return new ApiResourceObject(projects);
```

My question, in this case, is, how to properly create the `projects` variable. In your example, you defined it manually. Is there a way to automatically create the required structure? e.g., you would need some json-string like this:
```json
[
  {
    "id" : "abcd",
    "type": "projects",
    "attributes" : {
      "name" : "project a",
      // ...
    }
  }
]
```

How to you properly "serialize" your internal data to the required format?

Before, i was experimenting with this package here: https://github.com/SeyZ/jsonapi-serializer 
Defining a `Serializer` would allow for properly creating the desired structure. But what is the purpose of your package, if i need another one (with similar capabilities) to create the input for your package?

What i really like from your package, is that you actually must define an interface describing the data.. This is - in comparision to the mentioned other package - a benefit because it may be shared with client applications.. 

How do you cope with the problem of "serializing" your data before actually using your library? Would it be benefitial to "couple" this library with another one? Which one would you suggest?

All the best

**Comment by rmarganti** [comment]
This package's main purpose is the TypeScript Interfaces that it defines. Additionally, those have been defined from the perspective of a client and the responses it expects to receive from a server.

The support classes (ie. `ApiResourceObject`) are admittedly are half-baked and likely little use from a server's point-of-view. However, after a year+ of usage, I have some plans for improving everything contained in this package and expanding its usefulness (including serialization).

**Comment by johannesschobel** [comment]
Dear @rmarganti ,
just wanted to ask, if you have had time to work on the serialization process yet..
All the best

**Comment by rmarganti** [comment]
Sorry for delayed response; I've been working on prioritizing work here and in other projects. Because the main focus of this project is providing interfaces/types to be implemented elsewhere, I'm going to have prioritize that. For now serialization, etc will have to be put to the back burner.
